[package]
name = "rust-gamedev-bot"
version = "0.1.0"
authors = ["solarane <junmo.moon8@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.8"
fancy-regex = "0.3.5"
reqwest = { version = "0.10", features = ["json"] }
lazy_static = "1.4.0"
serde = "1"
serde_json = "1"
url = "2"